import { useEffect, useState } from 'react';
import PageCard from '../components/ui/PageCard';
import { useAuth } from '../context/AuthContext';
import { productService } from '../services/productService';
import { ledgerService } from '../services/ledgerService';
import { downloadCsv, exportPdfViaPrint } from '../utils/export';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 8)}01`;

const fmt = (n) => Number(n || 0).toFixed(2);
const fileSafe = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const formatDate = (iso) => {
  if (!iso) return '–';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
};

export default function CashBookPage() {
  const { user } = useAuth();
  const [generatedOn] = useState(() =>
    new Date().toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
      hour12: false,
    })
  );
  const [branches, setBranches] = useState([]);
  const [filters, setFilters] = useState({
    branchId: user?.role === 'main_admin' ? '' : String(user?.branchId || ''),
    startDate: monthStart,
    endDate: today,
  });
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const selectedBranchName =
    branches.find((branch) => String(branch.id) === String(filters.branchId))?.name || `Branch-${filters.branchId || 'NA'}`;

  const exportExcel = () => {
    if (!report) return;

    const rows = [
      ['Cash Book'],
      ['Branch', selectedBranchName],
      ['Date Range', `${filters.startDate || '-'} to ${filters.endDate || '-'}`],
      ['Generated On', generatedOn],
      ['Generated By', user?.fullName || user?.username || 'System'],
      ['Opening Balance', fmt(report.openingBalance)],
      ['Total Receipts (In)', fmt(report.totalDebit)],
      ['Total Payments (Out)', fmt(report.totalCredit)],
      ['Closing Balance', fmt(report.closingBalance)],
      [],
    ];

    (report.days || []).forEach((day) => {
      rows.push([formatDate(day.date)]);
      rows.push(['Opening', fmt(day.openingBalance)]);
      rows.push(['Side', 'Date', 'Ref No', 'Party / Description', 'Amount']);

      (day.entries || []).forEach((entry) => {
        if (entry.debit > 0) {
          rows.push(['Receipt', formatDate(entry.entryDate), entry.referenceNo || entry.referenceType || '-', entry.displayDescription || '-', fmt(entry.debit)]);
        }
        if (entry.credit > 0) {
          rows.push(['Payment', formatDate(entry.entryDate), entry.referenceNo || entry.referenceType || '-', entry.displayDescription || '-', fmt(entry.credit)]);
        }
      });

      rows.push(['', '', '', 'Receipts Total', fmt(day.totalDebit)]);
      rows.push(['', '', '', 'Payments Total', fmt(day.totalCredit)]);
      rows.push(['Closing', fmt(day.closingBalance)]);
      rows.push([]);
    });

    const fileName = `cash-book-${fileSafe(selectedBranchName)}-${filters.startDate || 'from'}-to-${filters.endDate || 'to'}.csv`;
    downloadCsv(rows, fileName);
  };

  useEffect(() => {
    if (user?.role !== 'main_admin') return;

    productService
      .getMeta()
      .then((data) => {
        const items = data.branches || [];
        setBranches(items);
        if (!filters.branchId && items[0]) {
          setFilters((prev) => ({ ...prev, branchId: String(items[0].id) }));
        }
      })
      .catch(() => {});
  }, [user?.role]); // eslint-disable-line react-hooks/exhaustive-deps

  const loadReport = async () => {
    if (!filters.branchId) {
      setError('Please select a branch.');
      return;
    }

    setLoading(true);
    setError('');
    try {
      const data = await ledgerService.getCashBook({
        branchId: Number(filters.branchId),
        startDate: filters.startDate || undefined,
        endDate: filters.endDate || undefined,
      });
      setReport(data);
    } catch (e) {
      setError(e.message || 'Failed to load cash book');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (filters.branchId) {
      loadReport();
    }
  }, [filters.branchId]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="dashboard-stack">
      <PageCard
        title="Cash Book"
        subtitle="Date-wise cash movements — receipts (in) and payments (out) from cash account"
        actions={
          <div className="inline-actions no-print">
            <button type="button" className="secondary-action-button" onClick={exportExcel} disabled={!report}>
              Export Excel
            </button>
            <button type="button" className="secondary-action-button" onClick={exportPdfViaPrint}>
              Export PDF
            </button>
          </div>
        }
      >
        {error ? <p className="error-text">{error}</p> : null}

        <div className="table-filters no-print">
          {user?.role === 'main_admin' ? (
            <label className="form-field" htmlFor="cashbook-branch">
              <span>Branch</span>
              <select
                id="cashbook-branch"
                value={filters.branchId}
                onChange={(e) => setFilters((prev) => ({ ...prev, branchId: e.target.value }))}
              >
                <option value="">— Select branch —</option>
                {branches.map((branch) => (
                  <option key={branch.id} value={branch.id}>
                    {branch.name}
                  </option>
                ))}
              </select>
            </label>
          ) : null}

          <label className="form-field" htmlFor="cashbook-start">
            <span>From</span>
            <input
              id="cashbook-start"
              type="date"
              value={filters.startDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, startDate: e.target.value }))}
            />
          </label>

          <label className="form-field" htmlFor="cashbook-end">
            <span>To</span>
            <input
              id="cashbook-end"
              type="date"
              value={filters.endDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, endDate: e.target.value }))}
            />
          </label>
        </div>

        <div className="inline-actions inline-actions--end no-print">
          <button type="button" className="primary-action-button" onClick={loadReport} disabled={loading}>
            {loading ? 'Loading…' : 'Load Ledger'}
          </button>
        </div>

        {report ? (
          <div className="dashboard-stack print-area">
            <div className="view-header">
              <strong>Cash Book</strong>
              <span>
                Branch: {selectedBranchName} | Date Range: {filters.startDate || '-'} to {filters.endDate || '-'} | Generated On: {generatedOn} | Generated By: {user?.fullName || user?.username || 'System'}
              </span>
            </div>

            <div className="totals-panel" style={{ maxWidth: 460 }}>
              <div className="totals-row">
                <span>Opening Balance</span>
                <strong>{fmt(report.openingBalance)}</strong>
              </div>
              <div className="totals-row">
                <span>Total Receipts (In)</span>
                <strong style={{ color: '#16a34a' }}>{fmt(report.totalDebit)}</strong>
              </div>
              <div className="totals-row">
                <span>Total Payments (Out)</span>
                <strong style={{ color: '#dc2626' }}>{fmt(report.totalCredit)}</strong>
              </div>
              <div className="totals-row totals-row--total">
                <span>Closing Balance</span>
                <strong>{fmt(report.closingBalance)}</strong>
              </div>
            </div>

            {report.days?.map((day) => {
              const creditEntries = day.entries.filter((entry) => Number(entry.credit) > 0);
              const debitEntries = day.entries.filter((entry) => Number(entry.debit) > 0);

              return (
                <div key={day.date} className="table-wrap table-wrap--full cashbook-day-card">
                  <div className="view-header">
                    <strong>{formatDate(day.date)}</strong>
                    <span>
                      Opening: {fmt(day.openingBalance)} | Closing: {fmt(day.closingBalance)}
                    </span>
                  </div>
                  <div className="cashbook-split-row">
                    <div className="table-wrap table-wrap--full cashbook-wrap">
                      <table className="data-table cashbook-table">
                        <thead>
                          <tr>
                            <th colSpan="4">Payments — Cash Out</th>
                          </tr>
                          <tr>
                            <th>Date</th>
                            <th>Ref No.</th>
                            <th>Description</th>
                            <th className="text-right">Amount</th>
                          </tr>
                        </thead>
                        <tbody>
                          {creditEntries.map((entry) => (
                            <tr key={`cr-${entry.id}`}>
                              <td>{formatDate(entry.entryDate)}</td>
                              <td>{entry.referenceNo || entry.referenceType || '–'}</td>
                              <td>{entry.displayDescription || entry.description || '–'}</td>
                              <td className="text-right ledger-credit">{fmt(entry.credit)}</td>
                            </tr>
                          ))}

                          {creditEntries.length === 0 ? (
                            <tr>
                              <td colSpan="4" className="empty-state-cell">No payments for this date.</td>
                            </tr>
                          ) : (
                            <tr className="table-total-row">
                              <td colSpan="3"><strong>Payments Total</strong></td>
                              <td className="text-right"><strong>{fmt(day.totalCredit)}</strong></td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>

                    <div className="table-wrap table-wrap--full cashbook-wrap">
                      <table className="data-table cashbook-table">
                        <thead>
                          <tr>
                            <th colSpan="4">Receipts — Cash In</th>
                          </tr>
                          <tr>
                            <th>Date</th>
                            <th>Ref No.</th>
                            <th>Description</th>
                            <th className="text-right">Amount</th>
                          </tr>
                        </thead>
                        <tbody>
                          {debitEntries.map((entry) => (
                            <tr key={`dr-${entry.id}`}>
                              <td>{formatDate(entry.entryDate)}</td>
                              <td>{entry.referenceNo || entry.referenceType || '–'}</td>
                              <td>{entry.displayDescription || entry.description || '–'}</td>
                              <td className="text-right ledger-debit">{fmt(entry.debit)}</td>
                            </tr>
                          ))}

                          {debitEntries.length === 0 ? (
                            <tr>
                              <td colSpan="4" className="empty-state-cell">No receipts for this date.</td>
                            </tr>
                          ) : (
                            <tr className="table-total-row">
                              <td colSpan="3"><strong>Receipts Total</strong></td>
                              <td className="text-right"><strong>{fmt(day.totalDebit)}</strong></td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              );
            })}

            {report.days?.length === 0 ? (
              <div className="table-wrap table-wrap--full">
                <table className="data-table">
                  <tbody>
                    <tr>
                      <td className="empty-state-cell">
                        No cash transactions found for the selected period.
                      </td>
                    </tr>
                  </tbody>
                </table>
              </div>
            ) : null}
          </div>
        ) : null}
      </PageCard>
    </div>
  );
}
