import { useEffect, useState } from 'react';
import PageCard from '../components/ui/PageCard';
import { useAuth } from '../context/AuthContext';
import { productService } from '../services/productService';
import { ledgerService } from '../services/ledgerService';
import { downloadCsv, downloadPdfFromPrintArea } from '../utils/export';

const today = new Date().toISOString().slice(0, 10);
const monthStart = `${today.slice(0, 8)}01`;

const fmt = (n) => Number(n || 0).toFixed(2);
const fileSafe = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
const formatDate = (iso) => {
  if (!iso) return '–';
  return new Date(iso).toLocaleDateString('en-GB', {
    day: '2-digit', month: 'short', year: 'numeric',
  });
};

const weekStart = () => {
  const d = new Date();
  const day = d.getDay();
  const diff = day === 0 ? 6 : day - 1;
  d.setDate(d.getDate() - diff);
  return d.toISOString().slice(0, 10);
};

export default function CashBookPage() {
  const { user } = useAuth();
  const [generatedOn] = useState(() =>
    new Date().toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
      hour12: false,
    })
  );
  const [branches, setBranches] = useState([]);
  const [filters, setFilters] = useState({
    branchId: user?.role === 'main_admin' ? '' : String(user?.branchId || ''),
    startDate: today,
    endDate: today,
  });
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [exportingPdf, setExportingPdf] = useState(false);

  const selectedBranchName =
    branches.find((branch) => String(branch.id) === String(filters.branchId))?.name || `Branch-${filters.branchId || 'NA'}`;

  const applyPreset = (preset) => {
    if (preset === 'today') {
      setFilters((prev) => ({ ...prev, startDate: today, endDate: today }));
    } else if (preset === 'week') {
      setFilters((prev) => ({ ...prev, startDate: weekStart(), endDate: today }));
    } else if (preset === 'month') {
      setFilters((prev) => ({ ...prev, startDate: monthStart, endDate: today }));
    }
  };

  const exportExcel = () => {
    if (!report) return;

    const rows = [
      ['Daily Cash Report'],
      ['Branch', selectedBranchName],
      ['Date Range', `${filters.startDate || '-'} to ${filters.endDate || '-'}`],
      ['Generated On', generatedOn],
      ['Generated By', user?.fullName || user?.username || 'System'],
      ['Opening Balance', fmt(report.openingBalance)],
      ['Total Cash In', fmt(report.totalDebit)],
      ['Total Cash Out', fmt(report.totalCredit)],
      ['Closing Balance', fmt(report.closingBalance)],
      [],
      ['Date', 'Opening', 'Cash In', 'Cash Out', 'Closing'],
    ];

    (report.days || []).forEach((day) => {
      rows.push([
        formatDate(day.date),
        fmt(day.openingBalance),
        fmt(day.totalDebit),
        fmt(day.totalCredit),
        fmt(day.closingBalance),
      ]);
    });

    rows.push([]);
    (report.days || []).forEach((day) => {
      rows.push([formatDate(day.date)]);
      rows.push(['Opening', fmt(day.openingBalance)]);
      rows.push(['Side', 'Date', 'Ref No', 'Party / Description', 'Amount']);

      (day.entries || []).forEach((entry) => {
        if (entry.debit > 0) {
          rows.push(['Cash In', formatDate(entry.entryDate), entry.referenceNo || entry.referenceType || '-', entry.displayDescription || '-', fmt(entry.debit)]);
        }
        if (entry.credit > 0) {
          rows.push(['Cash Out', formatDate(entry.entryDate), entry.referenceNo || entry.referenceType || '-', entry.displayDescription || '-', fmt(entry.credit)]);
        }
      });

      rows.push(['', '', '', 'Cash In Total', fmt(day.totalDebit)]);
      rows.push(['', '', '', 'Cash Out Total', fmt(day.totalCredit)]);
      rows.push(['Closing', fmt(day.closingBalance)]);
      rows.push([]);
    });

    const fileName = `daily-cash-report-${fileSafe(selectedBranchName)}-${filters.startDate || 'from'}-to-${filters.endDate || 'to'}.csv`;
    downloadCsv(rows, fileName);
  };

  const exportPdf = async () => {
    if (!report) return;
    setExportingPdf(true);
    setError('');
    try {
      const fileName = `daily-cash-report-${fileSafe(selectedBranchName)}-${filters.startDate || 'from'}-to-${filters.endDate || 'to'}.pdf`;
      await downloadPdfFromPrintArea(fileName, '.print-area');
    } catch (exportError) {
      setError(exportError.message || 'PDF export failed');
    } finally {
      setExportingPdf(false);
    }
  };

  useEffect(() => {
    if (user?.role !== 'main_admin') return;

    productService
      .getMeta()
      .then((data) => {
        const items = data.branches || [];
        setBranches(items);
        if (!filters.branchId && items[0]) {
          setFilters((prev) => ({ ...prev, branchId: String(items[0].id) }));
        }
      })
      .catch(() => {});
  }, [user?.role]); // eslint-disable-line react-hooks/exhaustive-deps

  const loadReport = async () => {
    if (!filters.branchId) {
      setError('Please select a branch.');
      return;
    }

    setLoading(true);
    setError('');
    try {
      const data = await ledgerService.getCashBook({
        branchId: Number(filters.branchId),
        startDate: filters.startDate || undefined,
        endDate: filters.endDate || undefined,
      });
      setReport(data);
    } catch (e) {
      setError(e.message || 'Failed to load daily cash report');
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (filters.branchId) {
      loadReport();
    }
  }, [filters.branchId]); // eslint-disable-line react-hooks/exhaustive-deps

  return (
    <div className="dashboard-stack">
      <PageCard
        title="Daily Cash Report"
        subtitle="Opening balance, cash in, cash out, and closing — from cash account (AST-001)"
        actions={
          <div className="inline-actions no-print">
            <button type="button" className="secondary-action-button" onClick={exportExcel} disabled={!report}>
              Export Excel
            </button>
            <button type="button" className="secondary-action-button" onClick={exportPdf} disabled={!report || exportingPdf}>
              {exportingPdf ? 'Exporting PDF…' : 'Export PDF'}
            </button>
          </div>
        }
      >
        {error ? <p className="error-text">{error}</p> : null}

        <div className="table-filters no-print">
          {user?.role === 'main_admin' ? (
            <label className="form-field" htmlFor="cashbook-branch">
              <span>Branch</span>
              <select
                id="cashbook-branch"
                value={filters.branchId}
                onChange={(e) => setFilters((prev) => ({ ...prev, branchId: e.target.value }))}
              >
                <option value="">– Select branch –</option>
                {branches.map((branch) => (
                  <option key={branch.id} value={branch.id}>
                    {branch.name}
                  </option>
                ))}
              </select>
            </label>
          ) : null}

          <label className="form-field" htmlFor="cashbook-start">
            <span>From</span>
            <input
              id="cashbook-start"
              type="date"
              value={filters.startDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, startDate: e.target.value }))}
            />
          </label>

          <label className="form-field" htmlFor="cashbook-end">
            <span>To</span>
            <input
              id="cashbook-end"
              type="date"
              value={filters.endDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, endDate: e.target.value }))}
            />
          </label>
        </div>

        <div className="inline-actions no-print" style={{ marginBottom: 12, flexWrap: 'wrap' }}>
          <button type="button" className="secondary-action-button" onClick={() => applyPreset('today')}>
            Today
          </button>
          <button type="button" className="secondary-action-button" onClick={() => applyPreset('week')}>
            This Week
          </button>
          <button type="button" className="secondary-action-button" onClick={() => applyPreset('month')}>
            This Month
          </button>
          <button type="button" className="primary-action-button" onClick={loadReport} disabled={loading} style={{ marginLeft: 'auto' }}>
            {loading ? 'Loading…' : 'Load Report'}
          </button>
        </div>

        {report ? (
          <div className="dashboard-stack print-area">
            <div className="view-header">
              <strong>Daily Cash Report</strong>
              <span>
                Branch: {selectedBranchName} | Date Range: {filters.startDate || '-'} to {filters.endDate || '-'} | Generated On: {generatedOn} | Generated By: {user?.fullName || user?.username || 'System'}
              </span>
            </div>

            <div className="page-stats-strip" style={{ gridTemplateColumns: 'repeat(4, minmax(0, 1fr))' }}>
              <div className="page-stat-tile page-stat-tile--primary">
                <span className="page-stat-tile__label">Opening</span>
                <strong className="page-stat-tile__value">{fmt(report.openingBalance)}</strong>
              </div>
              <div className="page-stat-tile page-stat-tile--success">
                <span className="page-stat-tile__label">Cash In</span>
                <strong className="page-stat-tile__value">{fmt(report.totalDebit)}</strong>
              </div>
              <div className="page-stat-tile page-stat-tile--danger">
                <span className="page-stat-tile__label">Cash Out</span>
                <strong className="page-stat-tile__value">{fmt(report.totalCredit)}</strong>
              </div>
              <div className="page-stat-tile page-stat-tile--warning">
                <span className="page-stat-tile__label">Closing</span>
                <strong className="page-stat-tile__value">{fmt(report.closingBalance)}</strong>
              </div>
            </div>

            <div className="totals-panel" style={{ maxWidth: 460 }}>
              <div className="totals-row">
                <span>Opening Balance</span>
                <strong>{fmt(report.openingBalance)}</strong>
              </div>
              <div className="totals-row">
                <span>Total Cash In</span>
                <strong style={{ color: '#16a34a' }}>+{fmt(report.totalDebit)}</strong>
              </div>
              <div className="totals-row">
                <span>Total Cash Out</span>
                <strong style={{ color: '#dc2626' }}>-{fmt(report.totalCredit)}</strong>
              </div>
              <div className="totals-row totals-row--total">
                <span>Closing Balance</span>
                <strong>{fmt(report.closingBalance)}</strong>
              </div>
              <p style={{ margin: '8px 0 0', fontSize: 12, color: '#64748b' }}>
                Closing = Opening + Cash In − Cash Out
              </p>
            </div>

            <div className="table-wrap table-wrap--full">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th className="text-right">Opening</th>
                    <th className="text-right">Cash In</th>
                    <th className="text-right">Cash Out</th>
                    <th className="text-right">Closing</th>
                  </tr>
                </thead>
                <tbody>
                  {(report.days || []).map((day) => (
                    <tr key={`sum-${day.date}`}>
                      <td>{formatDate(day.date)}</td>
                      <td className="text-right">{fmt(day.openingBalance)}</td>
                      <td className="text-right ledger-debit">{fmt(day.totalDebit)}</td>
                      <td className="text-right ledger-credit">{fmt(day.totalCredit)}</td>
                      <td className="text-right"><strong>{fmt(day.closingBalance)}</strong></td>
                    </tr>
                  ))}
                  {(report.days || []).length > 1 ? (
                    <tr className="table-total-row">
                      <td><strong>Period Total</strong></td>
                      <td className="text-right">{fmt(report.openingBalance)}</td>
                      <td className="text-right"><strong>{fmt(report.totalDebit)}</strong></td>
                      <td className="text-right"><strong>{fmt(report.totalCredit)}</strong></td>
                      <td className="text-right"><strong>{fmt(report.closingBalance)}</strong></td>
                    </tr>
                  ) : null}
                  {(report.days || []).length === 0 ? (
                    <tr>
                      <td colSpan="5" className="empty-state-cell">
                        No cash activity for the selected period.
                      </td>
                    </tr>
                  ) : null}
                </tbody>
              </table>
            </div>

            {(report.days || []).map((day) => {
              const creditEntries = (day.entries || []).filter((entry) => Number(entry.credit) > 0);
              const debitEntries = (day.entries || []).filter((entry) => Number(entry.debit) > 0);

              return (
                <div key={day.date} className="table-wrap table-wrap--full cashbook-day-card">
                  <div className="view-header">
                    <strong>{formatDate(day.date)}</strong>
                    <span>
                      Opening: {fmt(day.openingBalance)} | Cash In: {fmt(day.totalDebit)} | Cash Out: {fmt(day.totalCredit)} | Closing: {fmt(day.closingBalance)}
                    </span>
                  </div>
                  <div className="cashbook-split-row">
                    <div className="table-wrap table-wrap--full cashbook-wrap">
                      <table className="data-table cashbook-table">
                        <thead>
                          <tr>
                            <th colSpan="4">Cash Out</th>
                          </tr>
                          <tr>
                            <th>Date</th>
                            <th>Ref No.</th>
                            <th>Description</th>
                            <th className="text-right">Amount</th>
                          </tr>
                        </thead>
                        <tbody>
                          {creditEntries.map((entry) => (
                            <tr key={`cr-${entry.id}`}>
                              <td>{formatDate(entry.entryDate)}</td>
                              <td>{entry.referenceNo || entry.referenceType || '–'}</td>
                              <td>{entry.displayDescription || entry.description || '–'}</td>
                              <td className="text-right ledger-credit">{fmt(entry.credit)}</td>
                            </tr>
                          ))}

                          {creditEntries.length === 0 ? (
                            <tr>
                              <td colSpan="4" className="empty-state-cell">No cash out for this date.</td>
                            </tr>
                          ) : (
                            <tr className="table-total-row">
                              <td colSpan="3"><strong>Cash Out Total</strong></td>
                              <td className="text-right"><strong>{fmt(day.totalCredit)}</strong></td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>

                    <div className="table-wrap table-wrap--full cashbook-wrap">
                      <table className="data-table cashbook-table">
                        <thead>
                          <tr>
                            <th colSpan="4">Cash In</th>
                          </tr>
                          <tr>
                            <th>Date</th>
                            <th>Ref No.</th>
                            <th>Description</th>
                            <th className="text-right">Amount</th>
                          </tr>
                        </thead>
                        <tbody>
                          {debitEntries.map((entry) => (
                            <tr key={`dr-${entry.id}`}>
                              <td>{formatDate(entry.entryDate)}</td>
                              <td>{entry.referenceNo || entry.referenceType || '–'}</td>
                              <td>{entry.displayDescription || entry.description || '–'}</td>
                              <td className="text-right ledger-debit">{fmt(entry.debit)}</td>
                            </tr>
                          ))}

                          {debitEntries.length === 0 ? (
                            <tr>
                              <td colSpan="4" className="empty-state-cell">No cash in for this date.</td>
                            </tr>
                          ) : (
                            <tr className="table-total-row">
                              <td colSpan="3"><strong>Cash In Total</strong></td>
                              <td className="text-right"><strong>{fmt(day.totalDebit)}</strong></td>
                            </tr>
                          )}
                        </tbody>
                      </table>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        ) : null}
      </PageCard>
    </div>
  );
}
