import { useEffect, useMemo, useState } from 'react';
import PageCard from '../components/ui/PageCard';
import { useAuth } from '../context/AuthContext';
import Select from '../ui-kit/Select';
import { productService } from '../services/productService';
import { inventoryService } from '../services/inventoryService';
import { downloadCsv, downloadPdfFromPrintArea } from '../utils/export';

const formatDate = (value) => {
  if (!value) return '–';
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return value;
  return date.toLocaleDateString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
  });
};

const fmtQty = (value) => Number(value || 0).toFixed(4);
const fileSafe = (value) => String(value || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');

export default function ProductHistoryPage() {
  const { user } = useAuth();
  const [generatedOn] = useState(() =>
    new Date().toLocaleString('en-GB', {
      day: '2-digit', month: 'short', year: 'numeric',
      hour: '2-digit', minute: '2-digit', second: '2-digit',
      hour12: false,
    })
  );
  const [meta, setMeta] = useState({ branches: [], products: [] });
  const [filters, setFilters] = useState({
    branchId: user?.role === 'main_admin' ? '' : String(user?.branchId || ''),
    productId: '',
    startDate: '',
    endDate: '',
  });
  const [rows, setRows] = useState([]);
  const [summary, setSummary] = useState([]);
  const [searched, setSearched] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [exportingPdf, setExportingPdf] = useState(false);

  useEffect(() => {
    const loadMeta = async () => {
      try {
        const metaRes = await productService.getMeta();
        const products = await productService.getProducts({});
        const branches = metaRes.branches || [];
        setMeta({ branches, products: products || [] });
      } catch (e) {
        setError(e.message || 'Failed to load metadata');
      }
    };

    loadMeta();
  }, []);

  const loadHistory = async () => {
    if (!filters.branchId) {
      setError('Please select a branch');
      return;
    }

    setLoading(true);
    setError('');

    try {
      const result = await inventoryService.getProductHistory({
        branchId: Number(filters.branchId),
        productId: filters.productId ? Number(filters.productId) : undefined,
        startDate: filters.startDate || undefined,
        endDate: filters.endDate || undefined,
      });

      setRows(result.movements || []);
      setSummary(result.summary || []);
      setSearched(true);
    } catch (e) {
      setError(e.message || 'Failed to load product history');
    } finally {
      setLoading(false);
    }
  };

  const selectedBranchName = useMemo(() => {
    return meta.branches.find((branch) => String(branch.id) === String(filters.branchId))?.name || '—';
  }, [meta.branches, filters.branchId]);

  const exportExcel = () => {
    if (!searched) return;

    const rowsForExport = [
      ['Product History'],
      ['Branch', selectedBranchName],
      ['Product Filter', filters.productId ? (meta.products.find((p) => String(p.id) === String(filters.productId))?.name || filters.productId) : 'All products'],
      ['Date Range', `${filters.startDate || '-'} to ${filters.endDate || '-'}`],
      ['Generated On', generatedOn],
      ['Generated By', user?.fullName || user?.username || 'System'],
      [],
      ['Date', 'Product', 'SKU', 'Type', 'Source', 'Reference', 'Stock In', 'Stock Out', 'Running Stock'],
      ...rows.map((row) => [
        row.movementDate,
        row.productName,
        row.sku || '-',
        row.movementType === 'stock_in' ? 'Stock In' : 'Stock Out',
        row.source || '-',
        row.referenceNo || '-',
        row.quantityIn > 0 ? fmtQty(row.quantityIn) : '',
        row.quantityOut > 0 ? fmtQty(row.quantityOut) : '',
        fmtQty(row.runningQty),
      ]),
    ];

    const fileName = `product-history-${fileSafe(selectedBranchName)}-${filters.startDate || 'from'}-to-${filters.endDate || 'to'}.csv`;
    downloadCsv(rowsForExport, fileName);
  };

  const exportPdf = async () => {
    if (!searched) return;
    setExportingPdf(true);
    setError('');
    try {
      const fileName = `product-history-${fileSafe(selectedBranchName)}-${filters.startDate || 'from'}-to-${filters.endDate || 'to'}.pdf`;
      await downloadPdfFromPrintArea(fileName, '.print-area');
    } catch (exportError) {
      setError(exportError.message || 'PDF export failed');
    } finally {
      setExportingPdf(false);
    }
  };

  return (
    <div className="dashboard-stack">
      <PageCard
        title="Product History"
        subtitle="Track stock-in and stock-out movements by branch and product"
        actions={
          <div className="inline-actions no-print">
            <button type="button" className="secondary-action-button" onClick={exportExcel} disabled={!searched}>
              Export Excel
            </button>
            <button type="button" className="secondary-action-button" onClick={exportPdf} disabled={!searched || exportingPdf}>
              {exportingPdf ? 'Exporting PDF…' : 'Export PDF'}
            </button>
          </div>
        }
      >
        {error ? <p className="error-text">{error}</p> : null}

        <div className="table-filters no-print">
          <label className="form-field" htmlFor="history-branch">
            <span>Branch</span>
            <Select
              id="history-branch"
              value={filters.branchId}
              onChange={(e) => setFilters((prev) => ({ ...prev, branchId: e.target.value }))}
              options={[{ value: '', label: '— select branch —' }, ...(meta.branches || []).map((b) => ({ value: String(b.id), label: b.name }))]}
              disabled={user?.role !== 'main_admin'}
            />
          </label>

          <label className="form-field" htmlFor="history-product">
            <span>Product (optional)</span>
            <Select
              id="history-product"
              value={filters.productId}
              onChange={(e) => setFilters((prev) => ({ ...prev, productId: e.target.value }))}
              options={[{ value: '', label: 'All products' }, ...(meta.products || []).map((p) => ({ value: String(p.id), label: `${p.name} (${p.sku || 'N/A'})` }))]}
            />
          </label>

          <label className="form-field" htmlFor="history-start-date">
            <span>From date</span>
            <input
              id="history-start-date"
              type="date"
              value={filters.startDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, startDate: e.target.value }))}
            />
          </label>

          <label className="form-field" htmlFor="history-end-date">
            <span>To date</span>
            <input
              id="history-end-date"
              type="date"
              value={filters.endDate}
              onChange={(e) => setFilters((prev) => ({ ...prev, endDate: e.target.value }))}
            />
          </label>
        </div>

        <div className="inline-actions inline-actions--end no-print">
          <button type="button" className="primary-action-button" onClick={loadHistory} disabled={loading}>
            {loading ? 'Loading…' : 'Load History'}
          </button>
        </div>

        {searched ? (
          <>
            <div className="view-header">
              <strong>Product History Report</strong>
              <span>
                Branch: {selectedBranchName} | Date Range: {filters.startDate || '-'} to {filters.endDate || '-'} | Generated On: {generatedOn} | Generated By: {user?.fullName || user?.username || 'System'}
              </span>
            </div>

            <div className="totals-panel" style={{ maxWidth: 520 }}>
              <div className="totals-row">
                <span>Branch</span>
                <strong>{selectedBranchName}</strong>
              </div>
              <div className="totals-row">
                <span>Products in result</span>
                <strong>{summary.length}</strong>
              </div>
              <div className="totals-row">
                <span>Total movements</span>
                <strong>{rows.length}</strong>
              </div>
            </div>

            <div className="table-wrap table-wrap--full print-area">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Product</th>
                    <th>SKU</th>
                    <th>Type</th>
                    <th>Reference</th>
                    <th className="text-right">Stock In</th>
                    <th className="text-right">Stock Out</th>
                    <th className="text-right">Running Stock</th>
                  </tr>
                </thead>
                <tbody>
                  {rows.map((row, index) => (
                    <tr key={`${row.productId}-${row.referenceNo}-${index}`}>
                      <td>{formatDate(row.movementDate)}</td>
                      <td>{row.productName}</td>
                      <td>{row.sku || '–'}</td>
                      <td>
                        <span className={`badge ${row.movementType === 'stock_in' ? 'badge--green' : 'badge--gray'}`}>
                          {row.movementType === 'stock_in' ? 'Stock In' : 'Stock Out'}
                        </span>
                      </td>
                      <td>{row.referenceNo || '–'}</td>
                      <td className="text-right ledger-debit">{row.quantityIn > 0 ? fmtQty(row.quantityIn) : '–'}</td>
                      <td className="text-right ledger-credit">{row.quantityOut > 0 ? fmtQty(row.quantityOut) : '–'}</td>
                      <td className="text-right">{fmtQty(row.runningQty)}</td>
                    </tr>
                  ))}

                  {rows.length === 0 ? (
                    <tr>
                      <td colSpan="8" className="empty-state-cell">
                        No product movements found for selected filters.
                      </td>
                    </tr>
                  ) : null}
                </tbody>
              </table>
            </div>
          </>
        ) : null}
      </PageCard>
    </div>
  );
}